### PR TITLE
Run black/flake8 on our notebooks

### PR DESCRIPTION
**Pull request by benfred**
Run black-nb/flake8-nb on our notebooks, and add to the precommit hook

### CODE REVIEW

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Review by jperez999 — APPROVED** [review]

**Pull request merged**
