### PR TITLE
Add multihot for triton inference server

### PR DESCRIPTION
**Pull request by benfred**
This change adds the ability to export workflows containing list columns to triton,
by converting to the same format that the TF dataloader expects.

### CODE REVIEW

**Comment by rnyak** [comment]
@benfred I cannot run movielens-multihot-TF example. I am getting errors. 

1.  Ensemble model is loaded successfully to the server. The `config.pbtxt` file for ensemble model does not look correct to me. Dont we need `genres` column as input also? 
```
name: "movielens"
platform: "ensemble"
input {
  name: "movieId"
  data_type: TYPE_INT64
  dims: -1
  dims: 1
}
input {
  name: "userId"
  data_type: TYPE_INT64
  dims: -1
  dims: 1
}
output {
  name: "dense_3"
  data_type: TYPE_FP32
  dims: -1
  dims: 1
}
ensemble_scheduling {
  step {
    model_name: "movielens_nvt"
    model_version: -1
    input_map {
      key: "movieId"
      value: "movieId"
    }
    input_map {
      key: "userId"
      value: "userId"
    }
    output_map {
      key: "genres"
      value: "genres_nvt"
    }
    output_map {
      key: "movieId"
      value: "movieId_nvt"
    }
    output_map {
      key: "userId"
      value: "userId_nvt"
    }
  }
  step {
    model_name: "movielens_tf"
    model_version: -1
    input_map {
      key: "genres__nnzs"
      value: "genres__nnzs_nvt"
    }
    input_map {
      key: "genres__values"
      value: "genres__values_nvt"
    }
    input_map {
      key: "movieId"
      value: "movieId_nvt"
    }
    input_map {
      key: "userId"
      value: "userId_nvt"
    }
    output_map {
      key: "dense_3"
      value: "dense_3"
    }
  }
}
```
2. when I try to send request to NVT model, I get the following error from the following code:

```
for i, (name, col) in enumerate(columns):
    d = col.values_host.astype(col_dtypes[i])
    print(d)
    d = d.reshape(len(d),1)
    inputs.append(httpclient.InferInput(name, d.shape, np_to_triton_dtype(col_dtypes[i])))
    inputs[i].set_data_from_numpy(d)
    
# placeholder variables for the output
outputs = [httpclient.InferRequestedOutput(name) for name in workflow.column_group.columns]

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-45-7755e8763c02> in <module>
      2 
      3 for i, (name, col) in enumerate(columns):
----> 4     d = col.values_host.astype(col_dtypes[i])
      5     print(d)
      6     d = d.reshape(len(d),1)

/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py in values_host(self)
    331         <class 'numpy.ndarray'>
    332         """
--> 333         return self._column.values_host
    334 
    335     def serialize(self):

/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py in values_host(self)
    133         Return a numpy representation of the Column.
    134         """
--> 135         return self.data_array_view.copy_to_host()
    136 
    137     @property

/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py in data_array_view(self)
     76         View the data as a device array object
     77         """
---> 78         result = cuda.as_cuda_array(self.data)
     79         # Workaround until `.view(...)` can change itemsize
     80         # xref: https://github.com/numba/numba/issues/4829

/opt/conda/envs/rapids/lib/python3.8/site-packages/numba/cuda/api.py in as_cuda_array(obj, sync)
     71     """
     72     if not is_cuda_array(obj):
---> 73         raise TypeError("*obj* doesn't implement the cuda array interface.")
     74     else:
     75         return from_cuda_array_interface(obj.__cuda_array_interface__,

TypeError: *obj* doesn't implement the cuda array interface.
```

**Comment by benfred** [comment]
@rnyak We don't need the genres column as an input - the nvt model will look up the genres for each movie as part of the joinexternal op it does.

For your 2nd error : When creating the request for the nvt model, the return values won't map exactly to the workflow columns - since we return 2 columns  (values/nnzs) for the genres rather than 1

```python
import cudf
import tritonclient.http as httpclient
from tritonclient.utils import *

import nvtabular.inference.triton as nvt_triton

df = cudf.DataFrame({"userId": [1], "movieId": [1]})
inputs = nvt_triton.convert_df_to_triton_input(["userId", "movieId"], df, httpclient.InferInput)

outputs = [
    httpclient.InferRequestedOutput(col)
    for col in ["userId", "movieId", "genres__nnzs", "genres__values"]
]

with httpclient.InferenceServerClient("localhost:8000") as client:
    response = client.infer("movielens_nvt", inputs, request_id="1", outputs=outputs)

for col in ["userId", "movieId", "genres__nnzs", "genres__values"]:
    print(col, response.as_numpy(col), response.as_numpy(col).shape)
```
This will print out

```
userId [[1]] (1, 1)
movieId [[1]] (1, 1)
genres__nnzs [[5]] (1, 1)
genres__values [[ 3]
 [ 4]
 [ 5]
 [ 6]
 [10]] (5, 1)
```

I've tested the output of this with the movielens mh notebook you sent - and this all works. We do need to make a couple changes to the notebook (changing all dtypes of the keras inputs to int64).  Also when you start triton you really need to set ```--backend-config=tensorflow,version=2``` to specify that this is a TF2 model

**Comment by benfred** [comment]
rerun rests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by rnyak** [comment]
> @rnyak We don't need the genres column as an input - the nvt model will look up the genres for each movie as part of the joinexternal op it does.
> 
> For your 2nd error : When creating the request for the nvt model, the return values won't map exactly to the workflow columns - since we return 2 columns (values/nnzs) for the genres rather than 1
> 
> ```python
> import cudf
> import tritonclient.http as httpclient
> from tritonclient.utils import *
> 
> import nvtabular.inference.triton as nvt_triton
> 
> df = cudf.DataFrame({"userId": [1], "movieId": [1]})
> inputs = nvt_triton.convert_df_to_triton_input(["userId", "movieId"], df, httpclient.InferInput)
> 
> outputs = [
>     httpclient.InferRequestedOutput(col)
>     for col in ["userId", "movieId", "genres__nnzs", "genres__values"]
> ]
> 
> with httpclient.InferenceServerClient("localhost:8000") as client:
>     response = client.infer("movielens_nvt", inputs, request_id="1", outputs=outputs)
> 
> for col in ["userId", "movieId", "genres__nnzs", "genres__values"]:
>     print(col, response.as_numpy(col), response.as_numpy(col).shape)
> ```
> 
> This will print out
> 
> ```
> userId [[1]] (1, 1)
> movieId [[1]] (1, 1)
> genres__nnzs [[5]] (1, 1)
> genres__values [[ 3]
>  [ 4]
>  [ 5]
>  [ 6]
>  [10]] (5, 1)
> ```
> 
> I've tested the output of this with the movielens mh notebook you sent - and this all works. We do need to make a couple changes to the notebook (changing all dtypes of the keras inputs to int64). Also when you start triton you really need to set `--backend-config=tensorflow,version=2` to specify that this is a TF2 model

@benfred  that example works for generating nvtabular model input from raw data. I am trying to get response from ensemble model which takes raw data and generate softmax value, which works for when `num_rows = 1` but if I set `num_rows` 2, I get the following error:

```
# read in the workflow (to get input/output schema to call triton with)
batch = cudf.read_parquet("/model/data/valid.parquet", num_rows=2, columns=['userId', 'movieId'])
print(batch, "\n")

inputs = nvt_triton.convert_df_to_triton_input(["userId", "movieId"], batch, httpclient.InferInput)

# convert the batch to a triton inputs

# placeholder variables for the output
outputs = [grpcclient.InferRequestedOutput("dense_3")]

# build a client to connect to our server. 
# This InferenceServerClient object is what we'll be using to talk to Triton.
# make the request with tritonclient.grpc.InferInput object
with grpcclient.InferenceServerClient("10.110.20.127:8001") as client:
    response = client.infer("movielens", inputs, request_id="1",outputs=outputs)

print("predicted softmax result:\n", response.as_numpy('dense_3'))
```
---------------------------------------------------------------------------
InferenceServerException                  Traceback (most recent call last)
<ipython-input-93-7794945daec4> in <module>
     23 # make the request with tritonclient.grpc.InferInput object
     24 with grpcclient.InferenceServerClient("10.110.20.127:8001") as client:
---> 25     response = client.infer("movielens", inputs, request_id="1",outputs=outputs)
     26 
     27 print("predicted softmax result:\n", response.as_numpy('dense_3'))

/opt/conda/envs/rapids/lib/python3.8/site-packages/tritonclient/grpc/__init__.py in infer(self, model_name, inputs, model_version, outputs, request_id, sequence_id, sequence_start, sequence_end, priority, timeout, client_timeout, headers)
   1059             return result
   1060         except grpc.RpcError as rpc_error:
-> 1061             raise_error_grpc(rpc_error)
   1062 
   1063     def async_infer(self,

/opt/conda/envs/rapids/lib/python3.8/site-packages/tritonclient/grpc/__init__.py in raise_error_grpc(rpc_error)
     59 
     60 def raise_error_grpc(rpc_error):
---> 61     raise get_error_grpc(rpc_error) from None
     62 
     63 

InferenceServerException: [StatusCode.INTERNAL] in ensemble 'movielens', 2 root error(s) found.
  (0) Invalid argument: assertion failed: [Arguments to _from_row_partition do not form a valid RaggedTensor] [Condition x == y did not hold element-wise:] [x (model/dense_features/RaggedFromRowLengths/strided_slice_1:0) = ] [7] [y (model/dense_features/RaggedFromRowLengths/strided_slice:0) = ] [4]
	 [[{{node model/dense_features/RaggedFromRowLengths/assert_equal_1/Assert/AssertGuard/Assert}}]]
	 [[StatefulPartitionedCall/_139]]
  (1) Invalid argument: assertion failed: [Arguments to _from_row_partition do not form a valid RaggedTensor] [Condition x == y did not hold element-wise:] [x (model/dense_features/RaggedFromRowLengths/strided_slice_1:0) = ] [7] [y (model/dense_features/RaggedFromRowLengths/strided_slice:0) = ] [4]
	 [[{{node model/dense_features/RaggedFromRowLengths/assert_equal_1/Assert/AssertGuard/Assert}}]]
0 successful operations.
0 derived errors ignored.
````

Is this bcs the output of the `movilens_nvt` is a flattened array for the `genres__values` ?

**Comment by benfred** [comment]
@rnyak good catch! this last commit there should fix https://github.com/NVIDIA/NVTabular/pull/614/commits/445abf3093334143b9d4432bfc3d34be0c3aa686 (was a stupid typo)

**Review by rnyak — APPROVED** [review]

**Pull request merged**
