### PR TITLE
Support cpu-based Datasets in Groupby Op

### PR DESCRIPTION
**Pull request by rjzamora**
Small follow-up to #685

- Simplifies algorithm a bit to take advantage of `list` aggregation (now handles both `"list"` and `list` input from user)
- Supports operation on `Dataset` objects created with `cpu=True`

### CODE REVIEW

**Comment by rjzamora** [comment]
@benfred - I realized after the Groupby op went in that cudf already supports a `list` aggregation (but not by the name `"list"`).  This PR takes advantage of the existing functionality.  Since the same feature exists in Pandas, I also used this as an opportunity to provide cpu support.

**Comment by rjzamora** [comment]
rerun tests

**Review by karlhigley — APPROVED** [review]

**Review by benfred — APPROVED** [review]

**Comment by benfred** [comment]
rerun tests

**Comment by rjzamora** [comment]
rerun tests

**Pull request merged**
