### PR TITLE
Write output using fsspec

### PR DESCRIPTION
**Pull request by albert17**
Uses fsspec to write output in cloud storage systems

### CODE REVIEW

**Comment by benfred** [comment]
rerun tests

**Comment by albert17** [comment]
@benfred It looks like opening files using fsspec, and passing those file objects to the cudf ParquetWriter `(self.data_writers.append(pwriter(self.fs.open(path, "w"), compression=None)))` produces a runtime error:
```
@pytest.mark.parametrize("engine", ["csv", "parquet", "csv-no-header"])
    def test_shuffle_gpu(tmpdir, datasets, engine):
        num_files = 2
        paths = glob.glob(str(datasets[engine]) + "/*." + engine.split("-")[0])
        if engine == "parquet":
            df1 = cudf.read_parquet(paths[0])[mycols_pq]
        else:
            df1 = cudf.read_csv(paths[0], header=False, names=allcols_csv)[mycols_csv]
        shuf = ParquetWriter(tmpdir, num_out_files=num_files, shuffle=nvt.io.Shuffle.PER_PARTITION)
        shuf.add_data(df1)
        writer_files = shuf.data_paths
        shuf.close()
        if engine == "parquet":
            df3 = cudf.read_parquet(writer_files[0])[mycols_pq]
            df4 = cudf.read_parquet(writer_files[1])[mycols_pq]
        else:
>           df3 = cudf.read_parquet(writer_files[0])[mycols_csv]

tests/unit/test_io.py:53:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/io/parquet.py:250: in read_parquet
    use_pandas_metadata=use_pandas_metadata,
cudf/_lib/parquet.pyx:173: in cudf._lib.parquet.read_parquet
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   RuntimeError: cuDF failure at: /rapids/cudf/cpp/src/io/parquet/reader_impl.cu:227: Incorrect data source

cudf/_lib/parquet.pyx:223: RuntimeError
```

I see messages during the execution like
```
ValueError: write to closed file
Exception ignored in: 'iobase_data_sink.host_write'
ValueError: write to closed file
ValueError: write to closed file
Exception ignored in: 'iobase_data_sink.host_write'
```

 I am not sure what I should be doing. I have observed that for Datasets PyArrow is used: https://github.com/NVIDIA/NVTabular/blob/main/nvtabular/io/parquet.py#L76

**Comment by albert17** [comment]
After talking with Ayush Dattagupta, this should be already supported by ParquetWriter, so just passing the normal path should work. Testing and checking, and If it is the case I will close this PR.

**Comment by albert17** [comment]
As I stated before, this is built in the Parquet Writer.

I have tested in both in GCS and S3 and it works successfully.

We will have to figure this out for HugeCTR formats for v0.5

**Pull request closed without merging**
