### PR TITLE
[REVIEW] NVT-HugeCTR End2End Example

### PR DESCRIPTION
**Pull request by albert17**
* NVT/HugeCTR E2E Notebook running in P100(16GB) and V100(16GB) for DLRM 16K Batches with whole Criteo Dataset
  - Notebook with the code (criteo-hugectr.ipynb) and HugeCTR Json configuration file (dlrm_fp32_16k.json)
  - test_notebooks.py updated to include this notebook

* Docker CI/CD infrastructure needs to be updated to have HugeCTR installed. File shared with Julio privately.

### CODE REVIEW

**Comment by benfred** [comment]
Looks good!

Can you move the config file and the notebook to a subdirectory (like put both of these in ```examples/hugectr```) ? I want it to be made clear that the json config file goes with the notebook.

What do you think about publishing the dockerfile here too? We have a tensorflow dockerfile in ```examples/tensorflow/docker/Dockerfile``` as a point of reference

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
@benfred 

I have moved the notebook and json config file to `examples/hugectr`.

I cannot add Dockerfile support in `examples/hugectr` yet, since HugeCTR needs to move to github or at least release v2.2.1 so it is available in GitHub. I will do that as soon as possible. I could also add support (configuration files) for more networks and include a README.md (similar to tensorflow example). Maybe I can add this together in a future PR?

Also, it looks like there is a problem with the CI/CD right now? @jperez999 
```
Installing collected packages: nvtabular
  Attempting uninstall: nvtabular
    Found existing installation: nvtabular 0.1.1
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 421, in run
    pycompile=options.compile,
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 76, in install_given_reqs
    auto_confirm=True
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 684, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py", line 545, in from_dist
    link_pointer, dist.project_name, dist.location)
AssertionError: Egg-link /var/jenkins_home/workspace/nvtabular_tests/nvtabular does not match installed location of nvtabular (at /var/jenkins_home/workspace/nvtab_docs/nvtabular)
```

**Comment by benfred** [comment]
rerun tests

**Pull request merged**
