### PR TITLE
Handle hive-partitioning in NVTabular.dataset.Dataset

### LINKED ISSUE #642: [FEA] Partition output parquet files by a column
**Is your feature request related to a problem? Please describe.**
For a realistic temporal evaluation protocol, it is common to split users interactions/sessions by time windows (e.g.  hours, days, weeks,  months), so that models can be trained over a time window and evaluated for a future time window.

So, NVTabular should be able to export the parquet files partitioned by a column (which can be a feature extracted from a timestamp column by a `LambdaOp`, like hour, day, week or month)

**Describe the solution you'd like**
When the workflow exports the parquet files, they should be organized in folders named after the partition column values (e.g. "interaction_date=2021-03-05").
That is, each folder should contain parquet files whose rows have the same value for the partition column as in their folder name
```python
workflow.transform(dataset).to_parquet('base/path', partition_by='interaction_date')
```

**Additional context**
With PySpark, this can be accomplished as follows

```python
interactions_df.write.partitionBy('session_start_date') \
                     .parquet('base/path')
```
P.s. This issue was extracted from #355  , which is broader in scope, so that it is implemented independently.

### PR DESCRIPTION
**Pull request by rjzamora**
Closes #642 
Addresses global shuffle component of #641 

Thu purpose of this PR is to improve handling of hive-partitioned parquet data in NVTabular.  Since the Dataset API already uses `dask.dataframe.read_parquet`, there is currenlty no "correcness" issue with **reading** hive-partitioned data.  However, (1) there is no convenient mechanism to write hive-partitioned data, and (2) the read stage typically results in many small partitions (rather than a single partition for each input directory).

- **Solution to (1)**:  The `Dataset.to_parquet` method now supports a `partition_on=` argument.  This is designed to match the same option in `dask.dataframe`/`dask_cudf`.  If the user passes a list of 1+ columns with this argument, the output data will be shuffled at IO time into a distinct directory for each unique combination of those `partition_on` column values.  When multiple columns are use for partitioning (e.g. `["month", "day"]`), the directory structure is nested (so that the full path for an output file will look something like `"/month=Mar/day=30/part.0.parquet"`).
- **Solution to (2)**:  Since #641 will need a mechanism to ensure a unique mapping between specified column groups and ddf partitions, this PR adds a `Dataset.partition_by_keys` method to perform a global shuffle on the specified column group (`keys`) and return a new (shuffled) Dataset.  For general Dataset objects, this method will simply call `ddf.shuffle()` under the hood.  For Dataset objects that are backed by hive-partitioned data, however, we use the metadata stored in the file paths to avoid a full shuffle. In the future, this optimization can be pushed even further by directly agregating all IO tasks within the same hive-partition.  However, I suspect that shuch an optimization should be implemented in `dask.dataframe`.

**Example Usage**
```python
import pandas as pd
import dask.dataframe as dd
import dask
import nvtabular as nvt

path = "fake.data"

# Create a sample ddf
ddf = dask.datasets.timeseries(
    start="2000-01-01",
    end="2000-01-03",
    freq="600s",
    partition_freq="6h",
    seed=42,
).reset_index()
ddf['timestamp'] = ddf['timestamp'].dt.round('D').dt.day

# Convert to a Datset and write out hive-partitioned data to disk
keys = ["timestamp", "name"]
nvt.Dataset(ddf).to_parquet(path, partition_on=keys)
```

This will produce a directory structure like:
```
$ find fake.data/ -type d -print
fake.data/
fake.data/timestamp=1
fake.data/timestamp=1/name=Alice
fake.data/timestamp=1/name=Frank
fake.data/timestamp=1/name=Victor
fake.data/timestamp=1/name=George
fake.data/timestamp=1/name=Quinn
fake.data/timestamp=1/name=Kevin
fake.data/timestamp=1/name=Ursula
...
```

Then, you can read the data back in with NVT, and ensure that the ddf partitions are shuffled by `keys`:
```python
ds = nvt.Dataset(path, engine="parquet").shuffle_by_keys(keys)
ds.to_ddf().compute()
```
```
      id         x         y timestamp    name
0    991 -0.750009 -0.587392         1   Alice
1   1022  0.866823 -0.682096         1   Alice
2    991  0.467775  0.683211         1   Alice
3    967  0.534984 -0.931405         1     Bob
4    991 -0.149716 -0.651939         1     Bob
..   ...       ...       ...       ...     ...
25   964  0.843602  0.598580         3  Yvonne
26   961  0.853070 -0.987596         3  Yvonne
27   947  0.934162  0.190069         3  Yvonne
28  1024 -0.107280  0.662606         3  Yvonne
29  1006  0.169090 -0.784889         3   Zelda

[288 rows x 5 columns]
```

### CODE REVIEW

**Comment by rjzamora** [comment]
cc @gabrielspmoreira @benfred

**Comment by gabrielspmoreira** [comment]
Sounds great @rjzamora ! This PR will allow incremental training and evaluation of sequential recommender models and time series, as allows splitting data by time windows.

**Comment by rjzamora** [comment]
Is it possible that the dataloader CI failures are being caused by this PR?

**Comment by benfred** [comment]
> Is it possible that the dataloader CI failures are being caused by this PR?

I don't think so - we've had some flaky tests around this for a while now (https://github.com/NVIDIA/NVTabular/issues/397) , but for some reason these errors seem more common now

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Review by benfred — APPROVED** [review]

**Comment by rjzamora** [comment]
rerun tests

**Comment by karlhigley** [comment]
@jperez999 This CI error looks familiar and I think you tried to explain it to me, but I didn't fully understand what's causing it. Thoughts on how to resolve it?

**Comment by jperez999** [comment]
@karlhigley ok so I think... and follow me on this. So the reason for the error is that the median stat operator collects a median value of NA for the continuous columns (sometimes both x and y, sometimes just one of them). When we go to apply the NA value we hit the error we are seeing. I think this is because of the way we setup the dataset and the beginning here https://github.com/NVIDIA/NVTabular/blob/main/tests/conftest.py#L108-L112 This inserts the NA values, and I think we are seeing the random positions coincidentally land on the median indexes.

**Comment by jperez999** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
@karlhigley  @jperez999  @rjzamora  I think the NA failure in the unittests is unrelated to this PR - I spent some time debugging this and left me thoughts here https://github.com/NVIDIA/NVTabular/pull/687#issuecomment-811553045 . That PR has a 'fix' - but would like to figure out *why* this is happening

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
Rerun tests

**Pull request merged**
