### PR TITLE
[REVIEW] Update conda env files for cudf 0.16.0

### PR DESCRIPTION
**Pull request by karlhigley**
cudf 0.16.0 no longer supports CUDA 10.0 and has moved pandas and pyarrow dependencies forward to post-1.0 versions.

### CODE REVIEW

**Review by benfred — APPROVED** [review]
Awesome! thanks for taking care of this,

Did you check if the the recipe meta.yaml is also still valid? https://github.com/NVIDIA/NVTabular/blob/main/conda/recipes/meta.yaml#L30-L37

**Comment by karlhigley** [comment]
@benfred Added a commit to bump versions there too.

**Review by benfred — APPROVED** [review]

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Pull request merged**
