### PR TITLE
fix type error in dtypes

### PR DESCRIPTION
**Pull request by jperez999**

### CODE REVIEW

**Review by benfred — COMMENTED** [review]
The change looks good - but can we add a test that would catch this?

**Review by karlhigley — APPROVED** [review]

**Comment by karlhigley** [comment]
@benfred We agree that it should be tested, but we're not entirely sure how to write that test at the moment. Given the timeframe, we're inclined to merge a fix and address comprehensive testing as part of a further refactor that introduces standard NVT dtypes and provides translations between NVT dtypes and Python, Pandas, and cuDF types.

**Comment by karlhigley** [comment]
...yes, I am aware of how testing works and what the purpose is.

The repro is helpful though.

**Review by benfred — APPROVED** [review]

**Comment by benfred** [comment]
rerun tests

**Pull request merged**
