### PR TITLE
Simplify criteo conversion script

### PR DESCRIPTION
**Pull request by rjzamora**
Leverages recent improvements in #660 to simplify the Criteo-conversion example.

**TODO**:  

- [x] Establish if we need a simple mechanism/option to add a `".parquet"` (or custom) file suffix when `preserve_files=True` or an integer is specified for `output_files`.  **Update**: #675 added the `suffix=` argument to `to_parquet` with a `".parquet"` default.  So, this concern has been addressed.

### CODE REVIEW

**Comment by bschifferer** [comment]
I probably pushed my commit wrong  :/ - Based on this PR, I updated the criteo examples: https://github.com/NVIDIA/NVTabular/tree/rjzamora-simplify-criteo/examples/scaling-criteo

ToDos:
[x] Added download description
[x] Split NVTabular ETL out
[x] Add TensorFlow Training
[x] Add Inference with TensorFlow
[ ] Update PyTorch Examples
[ ] Update HugeCTR examples
[ ] Add HugeCTR Inference

**Comment by rjzamora** [comment]
Thanks @bschifferer - I merged in your changes and got `test_optimize_criteo` working locally (without the download step).  I'm not sure what the build failure in CI is all about.

**Comment by rjzamora** [comment]
rerun tests

**Comment by bschifferer** [comment]
I added TF, HugeCTR and FastAI version.
I added unittests for TF and FastAI - HugeCTR Python API is hard to write unit tests due to jupyter notebook functions

**Review by benfred — APPROVED** [review]

**Comment by benfred** [comment]
rerun tests

**Pull request merged**
