### PR TITLE
Update dev dependencies to run example notebooks with conda

### PR DESCRIPTION
**Pull request by karlhigley**
With these changes, it should be possible to create a conda env and get set up to run the notebooks from the root of the NVT repo as follows:

> conda env create -f=conda/environments/nvtabular_dev_cuda10.1.yml
> conda activate nvtabular_dev
> python -m ipykernel install --user --name=nvt
> pip install -e .
> jupyter notebook

Open an example notebook and select "nvt" as the kernel.

### CODE REVIEW

**Review by benfred — APPROVED** [review]
This looks good to me - we should update to rapids 0.18 now that its out (but we can do in a future PR=)

**Comment by karlhigley** [comment]
As written, this already installs 0.18, but we can tighten the version specifications.

**Comment by jperez999** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Pull request merged**
