### PR TITLE
Updates integration tests to use latest HugeCTR API

### PR DESCRIPTION
**Pull request by albert17**
Integration tests to use latest HugeCTR API.

### CODE REVIEW

**Comment by albert17** [comment]
Getting an error
```
    def _predict(dense_features, embedding_columns, row_ptrs, config_file, model_name):
        inference_params = InferenceParams(model_name = model_name,
                                        max_batchsize = 64,
                                        hit_rate_threshold = 0.5,
                                        dense_model_file = MODEL_DIR + "test_model/1/_dense_1900.model",
                                        sparse_model_files = [MODEL_DIR + "test_model/1/0_sparse_1900.model"],
                                        device_id = 0,
                                        use_gpu_embedding_cache = True,
                                        cache_size_percentage = 0.1,
                                        i64_input_key = True,
                                        use_mixed_precision = False)
>       inference_session = CreateInferenceSession(config_file, inference_params)
E       RuntimeError: [HCDEBUG][ERROR] Runtime error: Error: embeddings file not open for reading /var/tmp/HugeCTR/HugeCTR/src/inference/parameter_server.cpp:108
tests/integration/test_nvt_hugectr_training.py:370: RuntimeError
```

I have checked, and the file is there. @yingcanw Could you check if there is anything wrong in the config?

Also, @oyilmaz-nvidia, let me know what you think.

**Comment by yingcanw** [comment]
@albert17  In HugeCTR v3.1, HugeCTR will dump three files into "0_sparse_1900.model" folder, **key, emb_vector and slot_id** . 
  This error means that PS doesn't find the **key** or **emb_vector** model files in your "test_model/1/0_sparse_1900.model" folder. Could you please check your sparse folder to ensure the existence of the above two types of files and these files are Readable permission.

**Comment by albert17** [comment]
@yingcanw It looks like when using the old API the file where being generated, but after changing to the new API they are not. Where do we set the output path for them?

**Comment by albert17** [comment]
@yingcanw I found the problem, I was missing the parameters of the `fit` function `model.fit(max_iter=2000, display=100, eval_interval=200, snapshot=1900)`. Shout out to @bschifferer who discovered it.

Now I am getting another error
```
dense_features = [], embedding_columns = [26358, 163825, 219129, 5062, 167463, 219169, ...], row_ptrs = [0, 1, 2, 3, 4, 5, ...]
config_file = '/model/models/test_model/1/model.json', model_name = 'test_model'

    def _predict(dense_features, embedding_columns, row_ptrs, config_file, model_name):
        inference_params = InferenceParams(
            model_name=model_name,
            max_batchsize=64,
            hit_rate_threshold=0.5,
            dense_model_file=MODEL_DIR + "test_model/1/_dense_1900.model",
            sparse_model_files=[MODEL_DIR + "test_model/1/0_sparse_1900.model"],
            device_id=0,
            use_gpu_embedding_cache=True,
            cache_size_percentage=0.1,
            i64_input_key=True,
            use_mixed_precision=False,
        )
>       inference_session = CreateInferenceSession(config_file, inference_params)
E       RuntimeError: [HCDEBUG][ERROR] Runtime error: [Parser] No Such Key: nnz_per_slot /var/tmp/HugeCTR/HugeCTR/include/parser.hpp:321

tests/integration/test_nvt_hugectr_training.py:371: RuntimeError
```

**Comment by yingcanw** [comment]
@albert17 I have provided a example for you (prm: /gpfs/fs1/yingcanw/nvt_triton), you can check the details in slcak cdd-hugectr channel.

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
@yingcanw @benfred I got it working after syncing with @bschifferer

**Review by benfred — APPROVED** [review]

**Pull request merged**
