### PR TITLE
[REVIEW] Integration tests for TF inference notebooks

### PR DESCRIPTION
**Pull request by oyilmaz-nvidia**
This PR includes the integration tests for inference and notebook updates to be able to run notebooks from the integration tests.

### CODE REVIEW

**Comment by oyilmaz-nvidia** [comment]
@albert17 Can you please test this PR if it works with the CI?

**Review by albert17 — APPROVED** [review]
Tests are working

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Pull request merged**
