### PR TITLE
Add a 'download_file' utility function

### PR DESCRIPTION
**Pull request by benfred**
This adds a 'download_file' function that will download example files, optionally
unzip or untar them once downloaded, and display a progress bar in notebooks while
doing so. This replaces the 'wget/unzip' calls in notebooks.

### CODE REVIEW

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Review by jperez999 — APPROVED** [review]

**Comment by rnyak** [comment]
@benfred I tested your PR that seems it is working. Somehow, it displays a progress bar in the notebook, but the percentage does not change. something like that:
```
downloading ml-25m.zip: 0.00B [00:00, ?B/s]
unzipping files:   0%|          | 0/8 [00:00<?, ?files/s]
```

**Comment by benfred** [comment]
> Somehow, it displays a progress bar in the notebook, but the percentage does not change. something like that:

Seems like that was an issue with the JS version of tqdm in the TF container. 'Fixed' by defaulting to ascii progress bars only.

**Pull request merged**
