### PR TITLE
nvtabular 0.1.1

### PR DESCRIPTION
**Pull request by benfred**

### CODE REVIEW

**Comment by jperez999** [comment]
test

**Comment by jperez999** [comment]
run tests

**Comment by jperez999** [comment]
run tests

**Comment by jperez999** [comment]
run tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
run tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Pull request merged**
