### PR TITLE
Fix multi-GPU tests after the Horovod example scripts were removed

### PR DESCRIPTION
**Pull request by karlhigley**
I broke the build. Oops!

### CODE REVIEW

**Comment by karlhigley** [comment]
Not sure what's going on here, these tests pass when run independently but fail when run as part of the full test suite?

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Review by benfred — APPROVED** [review]

**Comment by karlhigley** [comment]
@benfred @jperez999 This passes locally, but is now failing with a NCCL comms error:
```
[1,0]:Traceback (most recent call last):
[1,0]:  File "./examples/multi-gpu-movielens/tf_trainer.py", line 134, in 
[1,0]:    loss_value = training_step(examples, labels, batch == 0)
[1,0]:  File "/conda/envs/rapids/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 867, in call
[1,0]:    result = self._call(*args, **kwds)
[1,0]:  File "/conda/envs/rapids/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 928, in _call
[1,0]:    return self._stateless_fn(*args, **kwds)
[1,0]:  File "/conda/envs/rapids/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3018, in call
[1,0]:    return graph_function._call_flat(
[1,0]:  File "/conda/envs/rapids/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
[1,0]:    return self._build_call_outputs(self._inference_function.call(
[1,0]:  File "/conda/envs/rapids/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
[1,0]:    outputs = execute.execute(
[1,0]:  File "/conda/envs/rapids/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
[1,0]:    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
[1,0]:tensorflow.python.framework.errors_impl.UnknownError:  ncclCommInitRank failed: invalid usage
[1,0]:\t [[{{node DistributedGradientTape_Allreduce/cond_10/then/_99/DistributedGradientTape_Allreduce/cond_10/HorovodAllreduce_gradient_tape_model_dense_3_BiasAdd_BiasAddGrad_0}}]] [Op:__inference_training_step_1698]
[1,0]:
[1,0]:Function call stack:
[1,0]:training_step
```

**Comment by jperez999** [comment]
rerun tests

**Review by jperez999 — APPROVED** [review]

**Pull request merged**
