### PR TITLE
repeat of pytorch on conts dl swapping under pointer

### PR DESCRIPTION
**Pull request by jperez999**
This solves a problem with continuous variables being swapped underneath pointers.

### CODE REVIEW

**Review by benfred — APPROVED** [review]
This looks good to me - is it possible to add a test that would catch this ?

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Review by benfred — APPROVED** [review]

**Comment by jperez999** [comment]
Unnecessary! Tensorflow version 2.5.0-dev20201207 fixes this.

**Pull request closed without merging**
