### PR TITLE
Fix for working with cudf 0.15

### PR DESCRIPTION
**Pull request by benfred**
Cudf 0.15 recently disabled iterating over the values of an index, which broke
a number of ops in nvtabular. (change https://github.com/rapidsai/cudf/pull/5340)
Fix by using values_host.

### CODE REVIEW

**Comment by benfred** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Pull request merged**
