### PR TITLE
[REVIEW] multi target support for TE

### PR DESCRIPTION
**Pull request by bschifferer**
Supporting multiple Target columns for Target Encoding. https://github.com/NVIDIA/NVTabular/issues/303

### CODE REVIEW

**Review by benfred — COMMENTED** [review]
Can you add a unittest that tests this functionality out?

**Comment by bschifferer** [comment]
run tests

**Comment by bschifferer** [comment]
> Can you add a unittest that tests this functionality out?

Added example in unittest

**Comment by benfred** [comment]
rerun tests

**Review by benfred — APPROVED** [review]

**Pull request merged**
