### PR TITLE
HugeCTR raw format support

### PR DESCRIPTION
**Pull request by oyilmaz-nvidia**
https://github.com/NVIDIA/NVTabular/issues/255

### CODE REVIEW

**Comment by oyilmaz-nvidia** [comment]
@albert17  I'll run some tests but can you also run the end2end workflow with binary format using this PR please?

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by oyilmaz-nvidia** [comment]
This is actually still a WIP PR. So, we'll need to check couple of things. Also, seems like HugeCTR team needs to update couple of things as well.

**Comment by albert17** [comment]
I tested for the whole Criteo dataset, and I run out of disk space when generating the output files (593G) with NVT.

I tested for 2 Criteo days (1 day for training, 1 day for validation) and NVT run successfully, roughly it looks like it is ~3x slower than writing parquet files. After that, I have tried to run HugeCTR for DLRM: It looks like the data format is read properly, but when the training starts I get a core dump (I have updated the config file for Raw format following the HugeCTR samples). This is the output;
```
[0.001, init_start, ]
HugeCTR Version: 2.2.1
Config file: dlrm_fp32_16k.json
[01d17h44m16s][HUGECTR][INFO]: algorithm_search is not specified using default: 1
[01d17h44m16s][HUGECTR][INFO]: Algorithm search: ON
Device 0: Tesla V100-DGXS-16GB
Device 1: Tesla V100-DGXS-16GB
[01d17h44m22s][HUGECTR][INFO]: Initial seed is 2914839218
[01d17h44m22s][HUGECTR][INFO]: cache_eval_data is not specified using default: 0
[01d17h44m22s][HUGECTR][INFO]: num_internal_buffers 1
[01d17h44m22s][HUGECTR][INFO]: num_internal_buffers 1
[01d17h44m22s][HUGECTR][INFO]: Vocabulary size: 2116453
[01d17h44m22s][HUGECTR][INFO]: max_vocabulary_size_per_gpu_=15500000
[01d17h44m22s][HUGECTR][INFO]: All2All Warmup Start
[01d17h44m22s][HUGECTR][INFO]: All2All Warmup End
[01d17h44m46s][HUGECTR][INFO]: gpu0 start to init embedding
[01d17h44m46s][HUGECTR][INFO]: gpu1 start to init embedding
[01d17h44m48s][HUGECTR][INFO]: gpu0 init embedding done
[01d17h44m48s][HUGECTR][INFO]: gpu1 init embedding done
[33128.3, init_end, ]
[33128.3, run_start, ]
HugeCTR training start:
[33128.4, train_epoch_start, 0, ]
Bus error (core dumped)
CPU times: user 708 ms, sys: 302 ms, total: 1.01 s
Wall time: 34.6 s
```

**Comment by oyilmaz-nvidia** [comment]
@albert17 Did you also add the ```“float_label_dense”: true``` into data layer?

**Comment by oyilmaz-nvidia** [comment]
Funny but we also need to set the number of samples in the data to num_samples parameter in data layer.

**Comment by oyilmaz-nvidia** [comment]
It's working for me now using 2 days of criteo data. 

I saw is the data size of binary file is 2.5x of original data (don't know why) and parquet writer is almost 3x faster.

**Comment by albert17** [comment]
I added the `num_samples `parameter as the sum of every file `num_rows `(for training and validation respectively). Is this the correct way to calculate it?

I didn't add the  `“float_label_dense”: true`, but I have just added and I still get the same error.

**Pull request closed without merging**
