### PR TITLE
Torch iteration break error Fix

### PR DESCRIPTION
**Pull request by jperez999**
This PR replaces the devices argument with a device argument because the dataloader is a process based component now. It also addresses the bug mentioned in issue  https://github.com/NVIDIA/NVTabular/issues/513. Creates a unit test to ensure proper functionality from now on.

### CODE REVIEW

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Review by karlhigley — APPROVED** [review]

**Comment by albert17** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Review by benfred — APPROVED** [review]

**Pull request merged**
