### PR TITLE
CPU Updates

### PR DESCRIPTION
**Pull request by albert17**
- [x] By default cpu=True in Dataset if cudf not installed
- [x] Method to get the library in dispatch so we can use it in the Notebooks
- [x] Added skalearn to requirements-dev
- [x] Installs dependencies when installing NVTabular trough pip
- [x] Install NVTabular trough conda withouth GPU support (Issue created: #959 for next release)
- [x] Fix JoinExternal Bugs: Did but got another Categorify error (#958 )

### CODE REVIEW

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
@benfred I am getting an error with versioneer: http://10.20.13.93:8080/job/nvtabular_tests/2841/console
`  AttributeError: module 'versioneer' has no attribute 'get_cmdclass'`
You added it in the past to avoid problems in CPU CI: https://github.com/NVIDIA/NVTabular/commit/52c8b1fdf041f62149ada2058fea39b34f7fcb60

**Comment by albert17** [comment]
rerun tests

**Review by benfred — APPROVED** [review]

**Pull request merged**
