### PR TITLE
Update requirements-dev.txt

### PR DESCRIPTION
**Pull request by benfred**

### CODE REVIEW

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by albert17** [comment]
@benfred We are missing `flake8-nb`, I just had to install it manually in the CI. Can we add it to the requirements-dev? If not I can add to the CI Dockerfile.

**Comment by benfred** [comment]
> @benfred We are missing `flake8-nb`, I just had to install it manually in the CI. Can we add it to the requirements-dev? If not I can add to the CI Dockerfile.

I've added flake8-nb and flask/flask_cors here

**Review by albert17 — APPROVED** [review]

**Pull request merged**
