### PR TITLE
Use versioneer for managing versions

### LINKED ISSUE #391: How to check installed NVTabular version
**Is your feature request related to a problem? Please describe.**
How to check installed NVTabular version

**Describe the solution you'd like**
import nvtabular
nvtabular.__version__ 

should display the installed version

**Describe alternatives you've considered**
N/A

**Additional context**
Currently missing
AttributeError: module 'nvtabular' has no attribute '__version__'

### PR DESCRIPTION
**Pull request by benfred**
Use the [versioneer package](https://github.com/python-versioneer/python-versioneer)
for managing our version string. This will pick up the appropiate string from
our git tags instead of requiring us to manually bump.

Closes #391

### CODE REVIEW

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Review by jperez999 — APPROVED** [review]

**Pull request merged**
