### PR TITLE
Rossmann: reproducing Kaggle LB top 10

### PR DESCRIPTION
**Pull request by vinhngx**
- modified data prep procedure, train/valid split to match fastai procedure
- fastai tabular model should produce a Kaggle top 10 LB result, i.e. RMSPE ~ 0.108
```
epoch | train_loss | valid_loss | exp_rmspe | time
-- | -- | -- | -- | --
0 | 0.063339 | 0.055790 | 0.268307 | 00:12
1 | 0.018981 | 0.017044 | 0.132904 | 00:12
2 | 0.012481 | 0.013901 | 0.120513 | 00:12
3 | 0.010040 | 0.013833 | 0.113656 | 00:12
4 | 0.008787 | 0.012254 | 0.109800 | 00:12
```

- Tensorflow: 
```
Epoch 1/10
1569/1569 [==============================] - 35s 22ms/step - loss: 0.0141 - rmspe_tf: 0.1277 - val_loss: 0.0199 - val_rmspe_tf: 0.1323
Epoch 2/10
1569/1569 [==============================] - 29s 18ms/step - loss: 0.0137 - rmspe_tf: 0.1267 - val_loss: 0.0124 - val_rmspe_tf: 0.1130
Epoch 3/10
1569/1569 [==============================] - 29s 19ms/step - loss: 0.0135 - rmspe_tf: 0.1243 - val_loss: 0.0120 - val_rmspe_tf: 0.1118
Epoch 4/10
1569/1569 [==============================] - 29s 19ms/step - loss: 0.0132 - rmspe_tf: 0.1234 - val_loss: 0.0180 - val_rmspe_tf: 0.1154
Epoch 5/10
1569/1569 [==============================] - 29s 19ms/step - loss: 0.0130 - rmspe_tf: 0.1223 - val_loss: 0.0159 - val_rmspe_tf: 0.1210
Epoch 6/10
1569/1569 [==============================] - 29s 18ms/step - loss: 0.0128 - rmspe_tf: 0.1207 - val_loss: 0.0131 - val_rmspe_tf: 0.1136
Epoch 7/10
1569/1569 [==============================] - 29s 19ms/step - loss: 0.0127 - rmspe_tf: 0.1205 - val_loss: 0.0121 - val_rmspe_tf: 0.1161
Epoch 8/10
1569/1569 [==============================] - 29s 19ms/step - loss: 0.0125 - rmspe_tf: 0.1197 - val_loss: 0.0186 - val_rmspe_tf: 0.1261
Epoch 9/10
1569/1569 [==============================] - 30s 19ms/step - loss: 0.0124 - rmspe_tf: 0.1189 - val_loss: 0.0173 - val_rmspe_tf: 0.1169
Epoch 10/10
1569/1569 [==============================] - 29s 18ms/step - loss: 0.0122 - rmspe_tf: 0.1178 - val_loss: 0.0122 - val_rmspe_tf: 0.1150


​```

### CODE REVIEW

**Comment by jperez999** [comment]
test

**Comment by jperez999** [comment]
run tests

**Comment by vinhngx** [comment]
sorry what tests are theres? are you running those?

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
Can one of the admins verify this patch?

**Comment by jperez999** [comment]
run tests

**Comment by jperez999** [comment]
run tests

**Comment by benfred** [comment]
This PR got messed up with the transition to the public repo - I've recreated with the commits here:  https://github.com/NVIDIA/NVTabular/pull/9

**Pull request closed without merging**
