### PR TITLE
[REVIEW] Add pre-commit configuration file

### PR DESCRIPTION
**Pull request by rjzamora**
Since CI is running black/isort/flake8, it is useful to provide a pre-commit config file in the repo.  This allows developers to automate black/isort/flake8 checks before they push it into CI (helps avoid wasted CI cycles on bad formatting).

Installing `pre-commit`:
```
pip install pre-commit
```

Installing the pre-commit hook scripts for NVTabular (from within NVTabular repo):
```
pre-commit install
```

Usage example (just commit changes like normal):
```
$ git add <files>
$ git commit -m "my commit msg"
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
[pre-commit-hooks 7753cc2] test change to python file
 1 file changed, 12 insertions(+), 21 deletions(-)
```

### CODE REVIEW

**Comment by jperez999** [comment]
<details><summary>Click to view CI Results</summary><pre>GitHub pull request #69 of commit 6784b92949955561ac845cf9e141f12c4ec5cdd3, no merge conflicts.
Running as SYSTEM
Setting status of 6784b92949955561ac845cf9e141f12c4ec5cdd3 to PENDING with url http://10.20.13.93:8080/job/nvtabular_tests/9/ and message: 'Pending'
Using context: Jenkins Unit Test Run
Building in workspace /var/jenkins_home/workspace/nvtabular_tests
using credential infra_1
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/NVIDIA/NVTabular.git # timeout=10
Fetching upstream changes from https://github.com/NVIDIA/NVTabular.git
 > git --version # timeout=10
using GIT_SSH to set credentials creds for infrastructure pipeline on public nvtabular repo
 > git fetch --tags --progress -- https://github.com/NVIDIA/NVTabular.git +refs/pull/69/*:refs/remotes/origin/pr/69/* # timeout=10
 > git rev-parse 6784b92949955561ac845cf9e141f12c4ec5cdd3^{commit} # timeout=10
Checking out Revision 6784b92949955561ac845cf9e141f12c4ec5cdd3 (detached)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 6784b92949955561ac845cf9e141f12c4ec5cdd3 # timeout=10
Commit message: "roll back ops.py change (it was to test pre-commit only)"
 > git rev-list --no-walk 5463b225426f8c26cc6517055f683c9b5a60b466 # timeout=10
[nvtabular_tests] $ /bin/bash /tmp/jenkins7889725316199757099.sh
No Path provided. Nothing to do 😴
ERROR: /var/jenkins_home/workspace/nvtabular/nvtabular/ops.py Imports are incorrectly sorted.
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for : : True
Logical operation result is TRUE
Running script  : #!/bin/bash
source activate rapids
cd /var/jenkins_home/
python test_res_push.py "https://api.GitHub.com/repos/NVIDIA/NVTabular/issues/$ghprbPullId/comments" "/var/jenkins_home/jobs/$JOB_NAME/builds/$BUILD_NUMBER/log" 
[nvtabular_tests] $ /bin/bash /tmp/jenkins6869932284284229499.sh
</pre></details>

**Comment by jperez999** [comment]
<details><summary>Click to view CI Results</summary><pre>GitHub pull request #69 of commit 744f4644964691ab043d031a9cee17a70efc8157, no merge conflicts.
Running as SYSTEM
Setting status of 744f4644964691ab043d031a9cee17a70efc8157 to PENDING with url http://10.20.13.93:8080/job/nvtabular_tests/10/ and message: 'Pending'
Using context: Jenkins Unit Test Run
Building in workspace /var/jenkins_home/workspace/nvtabular_tests
using credential infra_1
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/NVIDIA/NVTabular.git # timeout=10
Fetching upstream changes from https://github.com/NVIDIA/NVTabular.git
 > git --version # timeout=10
using GIT_SSH to set credentials creds for infrastructure pipeline on public nvtabular repo
 > git fetch --tags --progress -- https://github.com/NVIDIA/NVTabular.git +refs/pull/69/*:refs/remotes/origin/pr/69/* # timeout=10
 > git rev-parse 744f4644964691ab043d031a9cee17a70efc8157^{commit} # timeout=10
Checking out Revision 744f4644964691ab043d031a9cee17a70efc8157 (detached)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 744f4644964691ab043d031a9cee17a70efc8157 # timeout=10
Commit message: "use python black"
 > git rev-list --no-walk 6784b92949955561ac845cf9e141f12c4ec5cdd3 # timeout=10
[nvtabular_tests] $ /bin/bash /tmp/jenkins5414829809337104108.sh
No Path provided. Nothing to do 😴
ERROR: /var/jenkins_home/workspace/nvtabular/nvtabular/ops.py Imports are incorrectly sorted.
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for : : True
Logical operation result is TRUE
Running script  : #!/bin/bash
source activate rapids
cd /var/jenkins_home/
python test_res_push.py "https://api.GitHub.com/repos/NVIDIA/NVTabular/issues/$ghprbPullId/comments" "/var/jenkins_home/jobs/$JOB_NAME/builds/$BUILD_NUMBER/log" 
[nvtabular_tests] $ /bin/bash /tmp/jenkins6709455061131547846.sh
</pre></details>

**Comment by rjzamora** [comment]
Hmmm.. Not sure why pre-commit version of isort is disagreeing with standalone version...

**Comment by jperez999** [comment]
<details><summary>Click to view CI Results</summary><pre>GitHub pull request #69 of commit c074388cbbbb3683d8392480471f82ce781905be, no merge conflicts.
Running as SYSTEM
Setting status of c074388cbbbb3683d8392480471f82ce781905be to PENDING with url http://10.20.13.93:8080/job/nvtabular_tests/11/ and message: 'Pending'
Using context: Jenkins Unit Test Run
Building in workspace /var/jenkins_home/workspace/nvtabular_tests
using credential infra_1
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/NVIDIA/NVTabular.git # timeout=10
Fetching upstream changes from https://github.com/NVIDIA/NVTabular.git
 > git --version # timeout=10
using GIT_SSH to set credentials creds for infrastructure pipeline on public nvtabular repo
 > git fetch --tags --progress -- https://github.com/NVIDIA/NVTabular.git +refs/pull/69/*:refs/remotes/origin/pr/69/* # timeout=10
 > git rev-parse c074388cbbbb3683d8392480471f82ce781905be^{commit} # timeout=10
Checking out Revision c074388cbbbb3683d8392480471f82ce781905be (detached)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c074388cbbbb3683d8392480471f82ce781905be # timeout=10
Commit message: "testing isort"
 > git rev-list --no-walk 744f4644964691ab043d031a9cee17a70efc8157 # timeout=10
[nvtabular_tests] $ /bin/bash /tmp/jenkins3660530361190779694.sh
No Path provided. Nothing to do 😴
Skipped 3 files
============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /var/jenkins_home/workspace/nvtabular, inifile: setup.cfg
plugins: hypothesis-5.13.1, cov-2.8.1
collected 280 items

tests/unit/test_encoder.py ..............................                [ 10%]
tests/unit/test_groupby.py ............................................. [ 26%]
...                                                                      [ 27%]
tests/unit/test_io.py ...                                                [ 28%]
tests/unit/test_ops.py ................................................. [ 46%]
........................                                                 [ 55%]
tests/unit/test_tf_dataloader.py ......                                  [ 57%]
tests/unit/test_torch_dataloader.py .................................... [ 70%]
......                                                                   [ 72%]
tests/unit/test_workflow.py ............................................ [ 87%]
..................................                                       [100%]

----------- coverage: platform linux, python 3.7.6-final-0 -----------
Name                            Stmts   Miss Branch BrPart  Cover   Missing
---------------------------------------------------------------------------
nvtabular/__init__.py               6      0      0      0   100%
nvtabular/ds_writer.py             85      5     34      6    91%   26-27, 66->67, 67, 73->81, 98->99, 99-100, 103->105, 108->106, 117->116
nvtabular/encoder.py              153     25     56     11    77%   75->76, 76, 78->79, 79, 81->82, 82, 84->85, 85, 96->97, 97, 111->114, 138->139, 139, 141->142, 142, 150->153, 153, 162->163, 163, 266-271, 275-288, 304->308, 308
nvtabular/groupby.py              155     25     88     14    82%   75->76, 76, 79->80, 80, 86->87, 87, 90->91, 91, 94->96, 135->136, 136, 176->179, 183->exit, 202->205, 205, 216->219, 219, 236->242, 242-269, 272->273, 273-274, 275->276, 276-277, 291->292, 292-293
nvtabular/io.py                   263     73    104     11    68%   48->49, 49, 53->56, 56, 91, 113->119, 136->137, 137, 140->exit, 167->170, 187->198, 195->197, 272->273, 273, 281-287, 322->323, 323, 324->325, 325, 427-450, 453-468, 473-486, 489-511, 514-517, 521-529
nvtabular/ops.py                  467     97    124     14    75%   62->61, 93-97, 112->114, 385->388, 388, 465->466, 466, 469->470, 470-475, 501-502, 547-552, 556-557, 575->576, 576, 602->603, 603, 618->619, 619-621, 622->625, 625, 669->670, 670, 677->676, 718->719, 719, 749->750, 750, 810-819, 822-868, 873-875, 878, 881-882, 885-887, 950-957, 961, 974-982, 1065->1066, 1066, 1078-1082, 1085, 1090-1094
nvtabular/tf_dataloader.py        118     26     44     10    72%   17->19, 28-29, 32->35, 35-37, 72-77, 182->183, 183-184, 192->193, 193, 195->198, 198-201, 202->205, 205, 213->214, 214-217, 226->230, 257->258, 258, 263-264, 275->276, 276, 308
nvtabular/torch_dataloader.py     154     22     64     14    80%   47, 70->71, 71, 73->74, 74-75, 82-85, 91->92, 92-93, 101-102, 106->107, 107, 124->126, 130-134, 162->164, 164->166, 166->exit, 171->172, 172, 192->193, 193, 195->198, 238, 274->276, 276->277, 277, 278->279, 279, 294, 299
nvtabular/workflow.py             464     73    244     25    82%   32-33, 143->149, 149, 152-160, 188-190, 204-206, 220-222, 236-238, 263->264, 264, 315->317, 335->337, 347->348, 348, 384-394, 403->404, 404, 427->424, 484->485, 485, 494->495, 495-496, 503->506, 506, 536->539, 539, 550-553, 568->564, 573->574, 574, 597->598, 598, 682->683, 683-690, 736->738, 738->740, 740->741, 741-742, 743->753, 753, 761->763, 763->764, 764, 816->817, 817, 821->822, 822-828, 834->839, 839-842, 848->851, 851, 955-959
setup.py                            2      2      0      0     0%   18-20
---------------------------------------------------------------------------
TOTAL                            1867    348    758    105    78%
Coverage XML written to file coverage.xml

Required test coverage of 70% reached. Total coverage: 77.79%

======================= 280 passed in 164.07s (0:02:44) ========================
Performing Post build task...
Match found for : : True
Logical operation result is TRUE
Running script  : #!/bin/bash
source activate rapids
cd /var/jenkins_home/
python test_res_push.py "https://api.GitHub.com/repos/NVIDIA/NVTabular/issues/$ghprbPullId/comments" "/var/jenkins_home/jobs/$JOB_NAME/builds/$BUILD_NUMBER/log" 
[nvtabular_tests] $ /bin/bash /tmp/jenkins4891674211122403894.sh
</pre></details>

**Comment by rjzamora** [comment]
Got it - needed to add toml as an additional isort dependency.  Let me know how you feel about this addition @benfred @jperez999, we use it in cudf and dask and I find it very convenient (never have a black/isort/flake CI failure)

**Comment by rjzamora** [comment]
Thanks @benfred !

**Comment by benfred** [comment]
Thanks for this! Think we should all use this for development =)

**Pull request merged**
