### PR TITLE
Adding map function to KerasSequenceLoader

### PR DESCRIPTION
**Pull request by marcromeyn**
This makes the API of the TF dataloader a bit more familiar for the average TF-user, since `tf.data.Dataset` contains a similar function ([source](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#map)).

This new function can also be used to pass `sample_weight` to a keras-model, like requested in #667. Example:

```python
df = cudf.DataFrame(
    {
        "cat1": [1] * 100,
        "cat2": [2] * 100,
        "cat3": [3] * 100,
        "label": [0] * 100,
        "sample_weight": [1.0] * 100,
        "cont2": [2.0] * 100,
        "cont1": [1.0] * 100,
    }
)
path = os.path.join("tmp", "dataset.parquet")
df.to_parquet(path)
cat_names = ["cat3", "cat2", "cat1"]
cont_names = ["sample_weight", "cont2", "cont1"]
label_name = ["label"]

def add_sample_weight(features, labels, sample_weight_col_name="sample_weight"):
    sample_weight = tf.cast(features.pop(sample_weight_col_name) > 0, tf.float32)

    return features, labels, sample_weight

data_itr = KerasSequenceLoader(
    [path],
    cat_names=cat_names,
    cont_names=cont_names,
    batch_size=10,
    label_names=label_name,
    shuffle=False,
).map(add_sample_weight)

for X, y, sample_weight in data_itr:
    assert list(sample_weight.numpy()) == [1.0] * 10
```

### CODE REVIEW

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
The changes look good to me - but can you run black to format your code? 

We have a pre-commit hook available https://pre-commit.com/ that you can use to run black/isort/flake8 etc on every commit automatically.

**Review by jperez999 — APPROVED** [review]

**Comment by marcromeyn** [comment]
rerun tests

**Comment by karlhigley** [comment]
rerun tests

**Review by benfred — APPROVED** [review]

**Pull request merged**
